export const fruitOptions = [
  { value: 'Aguacates (4.7°C)', label: 'Aguacates (4.7°C)' },
  { value: 'Ajo (Ambiente)', label: 'Ajo (Ambiente)' },
  { value: 'Alcachofa (4.4°C)', label: 'Alcachofa (4.4°C)' },
  { value: 'Arandano azul (3.1°C)', label: 'Arandano azul (3.1°C)' },
  { value: 'Brócoli (2.2°C)', label: 'Brócoli (2.2°C)' },
  { value: 'Camote (14.2°C)', label: 'Camote (14.2°C)' },
  { value: 'Calabaza (3.6°C)', label: 'Calabaza (3.6°C)' },
  { value: 'Cereza (0.7°C)', label: 'Cereza (0.7°C)' },
  { value: 'Ciruela (3.1°C)', label: 'Ciruela (3.1°C)' },
  { value: 'Cebollas Nacional (9.4°C)', label: 'Cebollas Nacional (9.4°C)' },
  { value: 'Cebollas Americana (9.4°C)', label: 'Cebollas Americana (9.4°C)' },
  { value: 'Cebolla Seca (Ambiente)', label: 'Cebolla Seca (Ambiente)' },
  { value: 'Col de Bruselas (1.0°C)', label: 'Col de Bruselas (1.0°C)' },
  { value: 'Chabacano (1.7°C)', label: 'Chabacano (1.7°C)' },
  { value: 'Durazno (1.7°C)', label: 'Durazno (1.7°C)' },
  { value: 'Elote Dulce (1.7°C)', label: 'Elote Dulce (1.7°C)' },
  { value: 'Esparrago (4.6°C)', label: 'Esparrago (4.6°C)' },
  { value: 'Frambuesa (0.7°C)', label: 'Frambuesa (0.7°C)' },
  { value: 'Fresa (0.7°C)', label: 'Fresa (0.7°C)' },
  { value: 'Guayaba (7.7°C)', label: 'Guayaba (7.7°C)' },
  { value: 'Granada (5.6°C)', label: 'Granada (5.6°C)' },
  { value: 'Kiwi (1.7°C)', label: 'Kiwi (1.7°C)' },
  { value: 'Limón (6.9°C)', label: 'Limón (6.9°C)' },
  { value: 'Mandarina USA (6.4°C)', label: 'Mandarina USA (6.4°C)' },
  { value: 'Mandarina Peruana (6.4°C)', label: 'Mandarina Peruana (6.4°C)' },
  { value: 'Mandarina Nacional (6.4°C)', label: 'Mandarina Nacional (6.4°C)' },
  { value: 'Mango (2.2°C)', label: 'Mango (2.2°C)' },
  { value: 'Manzana Roja (3.1°C)', label: 'Manzana Roja (3.1°C)' },
  { value: 'Manzana Golden (3.1°C)', label: 'Manzana Golden (3.1°C)' },
  { value: 'Manzana Gala (3.1°C)', label: 'Manzana Gala (3.1°C)' },
  { value: 'Manzana Granny (3.1°C)', label: 'Manzana Granny (3.1°C)' },
  { value: 'Melón (2.8°C)', label: 'Melón (2.8°C)' },
  { value: 'Naranja (6.4°C)', label: 'Naranja (6.4°C)' },
  { value: 'Nectarina (1.7°C)', label: 'Nectarina (1.7°C)' },
  { value: 'Papaya (9.4°C)', label: 'Papaya (9.4°C)' },
  { value: 'Papa (9.4°C)', label: 'Papa (9.4°C)' },
  { value: 'Pepino (8.9°C)', label: 'Pepino (8.9°C)' },
  { value: 'Pera anjou (1.1°C)', label: 'Pera anjou (1.1°C)' },
  { value: 'Pera Asiatica (1.1°C)', label: 'Pera Asiatica (1.1°C)' },
  { value: 'Pera Bosc (1.1°C)', label: 'Pera Bosc (1.1°C)' },
  { value: 'Pera Bartlett (1.1°C)', label: 'Pera Bartlett (1.1°C)' },
  { value: 'Persimo (1.7°C)', label: 'Persimo (1.7°C)' },
  { value: 'Pimiento (7.2°C)', label: 'Pimiento (7.2°C)' },
  { value: 'Sandía (23.3°C)', label: 'Sandía (23.3°C)' },
  { value: 'Toronja (11.7°C)', label: 'Toronja (11.7°C)' },
  { value: 'Uva (1.2°C)', label: 'Uva (1.2°C)' },
  { value: 'Zanahoria (3.1°C)', label: 'Zanahoria (3.1°C)' },
  { value: 'Zarzamora (0.7°C)', label: 'Zarzamora (0.7°C)' }
]
